import { ScaledSheet, scale } from "react-native-size-matters";
import { COLORS, FONTS } from "../../home/constant";

const styles = ScaledSheet.create({
  newAccountContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.themeGray,
    marginBottom: scale(90),
  },
  keyboardAvoidingViewStyle: {
    flex: 1,
  },
  descriptionContainer: {
    marginTop: 16,
  },
  itemIcon: {
    width: 20,
    height: 20,
    resizeMode: "contain",
    marginLeft: 5,
    tintColor: COLORS.themGreen,
  },
  memberVeiw: {
    flexDirection: "row",
    marginVertical: 15,
    gap: 10,
    marginHorizontal: 12,
  },
  memberText: {
    fontSize: 18,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
    alignSelf: "center",
  },
  headerTrainer: { flexDirection: "row" },
  img: { width: 60, height: 60, alignSelf: "center" },
  userHeader: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 100,
    position: "absolute",
    top: 50, // Adjust this value to position it at the top
    left: 0,
    right: 0,
    zIndex: 2,
    paddingHorizontal: 5,
    flex: 1, // Adjust as needed
    alignSelf: "flex-start",
    backgroundColor: COLORS.transparent,
  },
  userIcon: {
    height: scale(30),
    width: scale(30),
    resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 10,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  colorText: {
    color: COLORS.themGreen,
    fontSize: 25,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_BOLD,
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    height: 40,
  },
  smallIcon: {
    width: scale(12),
    height: scale(11),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    flexDirection: "row",
  },
  largeTextStyle: {
    color: COLORS.white,
    fontSize: 15,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  informationTextStyle: {
    color: COLORS.white,
    fontSize: 18,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  sessionIcon: {
    width: scale(25),
    height: scale(25),
    resizeMode: "contain",
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    height: scale(45),
    alignSelf: "center",
    marginTop: 10,
  },
  userHeaderList: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 70,
    alignSelf: "flex-start",
    width: "100%",
    marginTop: 10,
  },
  userText: {
    fontSize: 20,
    fontFamily: FONTS.ARCHI_BOLD,
    color: COLORS.white,
    alignSelf: "center",
    marginTop: 10,
  },
  containerUser: {
    width: scale(330),
    backgroundColor: COLORS.gray1,
    paddingVertical: 20,
    borderRadius: 10,
    marginVertical: 20,
    alignSelf: "center",
  },
  itemContainer: {
    marginLeft: 5,
  },
  imagePlace: {
    width: 65,
    height: 65,
  },
  informationImage: {
    width: 20,
    height: 20,
    tintColor: COLORS.white,
    alignSelf: "center",
  },
  rightIcon: {
    width: 15,
    height: 15,
    tintColor: COLORS.lightWhite,
    alignSelf: "center",
  },
  imageList: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  listView: {
    flexDirection: "row",
    width: "95%",
    backgroundColor: COLORS.gray1,
    height: 50,
    borderRadius: 10,
    paddingHorizontal: 10,
    alignContent: "center",
    justifyContent: "space-between",
    alignSelf: "center",
  },
  secondaryButton: {
    backgroundColor: COLORS.themGreen,
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-evenly",
    marginHorizontal: 20,
    height: 40,
  },
  secondaryButtonText: {
    color: COLORS.black,
    fontSize: 15,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  textInput: {
    height: 40,
    width: "80%",
    borderWidth: 0.5,
    borderColor: COLORS.borderColor,
    borderRadius: 10,
    color: COLORS.white,
    paddingHorizontal: 10,
  },
  addlistView: {
    flexDirection: "row",
    paddingHorizontal: 10,
    justifyContent: "space-between",
    marginVertical: 15,
  },
  deleteImg: { width: 15, height: 17, alignSelf: "flex-end" },
  containerHeader: {
    backgroundColor: COLORS.gray1,
    marginHorizontal: 10,
    borderRadius: 10,
    marginVertical: 1,
    paddingVertical: 1,
  },
  timeList: {
    paddingHorizontal: 10,
    gap: 5,
    backgroundColor: COLORS.gray1,
    marginHorizontal: 10,
    borderRadius: 10,
    marginVertical: 5,
    paddingVertical: 10,
    gap: 10,
  },
  textUser: {
    // height: 40,
    width: "85%",
    borderWidth: 0.5,
    borderColor: COLORS.borderColor,
    borderRadius: 10,
    color: COLORS.white,
    alignSelf: "center",
    paddingHorizontal: 10,
  },
  row: {
    flexDirection: "row",
    width: "95%",
    paddingHorizontal: 10,
    gap: 5,
    marginVertical: 10,
  },
  editImage: { width: 15, height: 15 },
  horizontalLine: {
    borderWidth: 0.5,
    borderColor: COLORS.borderColor,
    marginVertical: scale(10),
    width: "98%",
    alignSelf: "center",
  },
  buttonView: {
    alignSelf: "flex-end",
    marginRight: 20,
    flexDirection: "row",
    marginTop: 10,
    gap: 20,
  },
  extraView: {
    width: 15,
    height: 15,
    borderWidth: 1,
    borderColor: COLORS.lightWhite,
    justifyContent: "center",
    borderRadius: 5,
    alignSelf: "center",
    marginTop: 10,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.transparentBlack,
  },
  modalContent: {
    backgroundColor: COLORS.gray1,
    paddingVertical: 30,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
  },
  modalImage: {
    width: scale(70),
    height: scale(70),
  },
  successImage: {
    width: scale(110),
    height: scale(110),
  },

  modalText: {
    // width: scale(210),
    fontSize: 20,
    textAlign: "center",
    fontWeight: "800",
    marginVertical: 40,
    color: COLORS.white,
  },
  starImageStyle: {
    width: 30,
    height: 30,
    marginLeft: 10,
    alignSelf: "center",
    // resizeMode: 'cover',
  },
  textStyle: {
    width: 325,
    height: 90,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 30,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
  },
  smallContainer: {
    width: 250,
    height: 10,
    justifyContent: "center",
    marginTop: 20,
    borderRadius: 10,
    flexDirection: "row",
  },
  crossImage: {
    width: scale(10),
    height: scale(10),
    resizeMode: "contain",
  },
  crossIconView: {
    width: scale(15),
    padding: scale(6),
    position: "absolute",
    top: 1,
    right: 5,
    alignItems: "flex-end",
    zIndex: 1,
  },
  smallPlusIcon: {
    width: 10,
    height: 10,
    tintColor: COLORS.lightWhite,
    alignSelf: "center",
  },
  editView: {
    width: scale(20),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.themGreen,
    height: scale(20),
    alignSelf: "center",
    borderRadius: scale(25),
    position: "absolute",
    top: scale(53),
    right: scale(135),
    zIndex: 1,
  },
  rejectedIcon: {
    width: 8,
    height: 8,
    resizeMode: "contain",
  },
  headerText: {
    fontSize: 18,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
  },
  AddIconStyle: {
    width: scale(56),
    height: scale(56),
    backgroundColor: COLORS.gray1,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 15,
  },
  modalContent: {
    backgroundColor: COLORS.gray1,
    paddingVertical: 30,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
  },
  modalImage: {
    width: scale(70),
    height: scale(70),
  },
  modalText: {
    // width: scale(210),
    fontSize: 14,
    textAlign: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.black,
    alignSelf: "center",
  },
  starImageStyle: {
    width: 30,
    height: 30,
    marginLeft: 10,
    alignSelf: "center",
    // resizeMode: 'cover',
  },
  textStyle: {
    width: 325,
    height: 90,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 30,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
  },
  smallModalContainer: {
    width: 250,
    height: 30,
    justifyContent: "center",
    marginVertical: 30,
    borderRadius: 10,
  },
  imageHolder: {
    width: scale(17),
    height: scale(17),
    resizeMode: "contain",
  },
  doneText: {
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    marginRight: 45,
  },
  modalTextUpload: {
    textAlign: "center",
    fontSize: 20,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
    marginLeft: scale(4),
    marginVertical: 10,
  },
  buttonColor: {
    alignSelf: "flex-end",
    marginRight: 20,
    flexDirection: "row",
    gap: 20,
    marginTop: 10,
  },
  editButtonView: {
    borderRadius: 99,
    backgroundColor: "#CCFF00",
    height: 20,
    width: 20,
    position: "absolute",
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  editIconStyle: {
    height: 12,
    width: 12,
  },
  hashView: {
    width: scale(100),
    backgroundColor: COLORS.themeGray,
    alignSelf: "center",
    paddingVertical: scale(3),
    borderRadius: scale(5),
    marginTop: scale(8),
  },
});

export default styles;
