import { ScaledSheet, scale, verticalScale } from "react-native-size-matters";
import { COLORS } from "../constant";
import { FONTS } from "../constant";

const styles = ScaledSheet.create({
  newAccountContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: COLORS.themeGray,
    justifyContent: "center",
    paddingVertical: 10,
    marginBottom: 80,
  },
  keyboardAvoidingViewStyle: {
    flex: 1,
  },
  descriptionContainer: {
    marginTop: 16,
  },
  touchableView: {
    width: scale(140),
    height: scale(80),
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.lightBlack,
    justifyContent: "space-around",
    alignItems: "center",
    margin: 20,
    backgroundColor: COLORS.lightBlack,
  },
  selectedView: {
    borderColor: COLORS.themGreen,
    backgroundColor: COLORS.themGreen,
  },
  text: {
    marginLeft: scale(7),
    fontSize: 13,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    flexWrap: "wrap",
    maxWidth: "100%",
  },
  selectedText: {
    fontSize: 14,
    color: COLORS.black,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    flexWrap: "wrap",
    maxWidth: "100%",
  },
  dumbleImg: {
    width: 32,
    height: 31,
    resizeMode: "cover",
  },
  bananaImg: {
    width: 50,
    height: 40,
    resizeMode: "cover",
  },
  searchView: {
    // alignContent: "center",
    // alignSelf: "center",
    // alignItems: "center",
    marginTop: 0,
  },
  bodyView: {
    alignContent: "center",
    alignSelf: "center",
    alignItems: "center",
    marginLeft: 20,
    marginRight: 30,
    flexDirection: "row",
  },
  headerBodyView: {
    alignContent: "center",
    alignSelf: "center",
    alignItems: "center",
  },
  horizontalListContainer: {
    flexGrow: 1,
    paddingBottom: scale(80),
    alignSelf: "center",
  },
  headerWrite: {
    fontSize: 26,
    fontFamily: FONTS.ARCHI_BOLD,
    color: COLORS.themGreen,
    alignSelf: "center",
    marginTop: 20,
  },
  addText: {
    fontSize: 26,
    fontFamily: FONTS.ARCHI_BOLD,
    color: COLORS.white,
    alignSelf: "center",
  },
  addTouchable: {
    width: 30,
    height: 30,
    borderRadius: 4,
    backgroundColor: COLORS.calendarColor,
    marginLeft: 10,
  },
  buttonView: {
    flexDirection: "row",
    gap: 20,
    padding: 30,
    marginRight: 30,
    justifyContent: "center",
    gap: 10,
  },
  userIcon: {
    height: scale(30),
    width: scale(30),
    resizeMode: "contain",
    alignSelf: "center",
    // marginBottom: 10,
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  reservTextHead: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginLeft: scale(6),
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    height: 30,
  },
  smallIcon: {
    width: scale(12),
    height: scale(11),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  largeTextStyle: {
    color: COLORS.white,
    fontSize: 15,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  colorText: {
    color: COLORS.themGreen,
    fontSize: 25,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    height: scale(35),
    alignSelf: "center",
  },
  sessionIcon: {
    width: scale(15),
    height: scale(11),
    resizeMode: "contain",
  },
  userHeader: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 100,
    position: "absolute",
    top: 50, // Adjust this value to position it at the top
    left: 0,
    right: 0,
    zIndex: 2,
    paddingHorizontal: 5,
    flex: 1, // Adjust as needed
    alignSelf: "flex-start",
    backgroundColor: COLORS.transparent,
  },
  addYellowview: {
    backgroundColor: COLORS.themGreen,
    height: scale(44),
    position: "absolute",
    bottom: scale(20),
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
    paddingHorizontal: 18,
    gap: 10,
    flex: 1,
    alignSelf: "center",
  },
  pluseText: {
    color: "black",
    fontSize: 30,
    fontWeight: "400",
  },
  centeredView: {
    width: "100%",
    position: "absolute",
    borderRadius: 9,
    padding: 1,
    alignItems: "flex-end",
    flex: 1,
    zIndex: 1,
    height: "100%",
    alignContent: "flex-end",
    justifyContent: "flex-end",
    bottom: 0,
    // backgroundColor:'pink'
  },
  modalPlusView: { marginBottom: 130, marginRight: 85 },
  modalView: {
    width: scale(160),
    flexDirection: "row",
    borderRadius: 25,
    padding: 5,
    alignItems: "center",
    elevation: 5,
  },
  modalWorkoutView: {
    width: scale(110),
    flexDirection: "row",
    borderRadius: 25,
    padding: 10,
    alignItems: "center",
    elevation: 5,
    backgroundColor: COLORS.calendarColor,
    borderColor: COLORS.themGreen,
    borderWidth: 2,
  },
  modalText: {
    textAlign: "center",
    fontSize: scale(12),
    color: COLORS.black,
    marginLeft: scale(4),
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  modelIcon: {
    width: scale(15),
    height: scale(15),
    resizeMode: "contain",
  },
  workoutButtonContainer: {
    position: "absolute",
    bottom: 100,
    width: "100%",
    zIndex: 2,
  },
  scrollV: { marginTop: scale(-140) },
  headerTrainer: { flexDirection: "row", zIndex: 3, height: scale(200) },
  modelViewcontainer: {
    flex: 1,
    backgroundColor: COLORS.themeGray,
    justifyContent: "flex-start",
  },
  reviewModelView: {
    flex: 1,
    backgroundColor: COLORS.themeGray,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmModal: {
    width: scale(330),
    alignSelf: "center",
    justifyContent: "flex-start",
    borderRadius: scale(8),
    paddingVertical: scale(50),
    backgroundColor: COLORS.gray1,
    marginTop: scale(80),
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 20,
  },
  signature: {
    borderColor: "#000",
    borderWidth: 1,
    height: 100,
    marginTop: scale(200),
    backgroundColor: "red",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 20,
  },
  crossIconView: {
    width: scale(15),
    position: "absolute",
    top: 0,
    right: 10,
    alignItems: "flex-end",
    zIndex: 1,
    padding: 16,
  },
  crossImage: {
    width: scale(12),
    height: scale(11),
    resizeMode: "contain",
  },
  horizontalLine: {
    borderWidth: 1,
    borderColor: COLORS.gray,
    marginVertical: scale(8),
    width: scale(300),
    alignSelf: "center",
  },
  container: {
    flexDirection: "row",

    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 10,
  },
  starImageStyle: {
    width: 15,
    height: 15,
    marginLeft: 5,
    alignSelf: "center",
  },
  textStyle: {
    width: 305,
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 0,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
    alignSelf: "center",
  },
  lottie: {
    width: 100,
    height: 100,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.transparentBlack,
  },
  modalContent: {
    backgroundColor: COLORS.gray1,
    paddingVertical: 30,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
  },
  modalImage: {
    width: scale(70),
    height: scale(70),
  },
  modalText: {
    // width: scale(210),
    fontSize: 14,
    textAlign: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.black,
    alignSelf: "center",
  },
  smallContainer: {
    width: 250,
    height: 30,
    justifyContent: "center",
    marginVertical: 30,
    borderRadius: 10,
  },
  modalTextUpload: {
    textAlign: "center",
    fontSize: 20,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
    marginLeft: scale(4),
    marginVertical: 10,
  },
  imageHolder: {
    width: scale(17),
    height: scale(17),
    resizeMode: "contain",
  },
  doneText: {
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    marginRight: 45,
  },
  selectedText: {
    fontSize: 16,
    color: COLORS.themGreen,
    fontFamily: FONTS.ARCHI_BOLD,
  },
  flexContainer: {
    width: scale(155),
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.themGreen,
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
    backgroundColor: COLORS.themGreen,
    flexDirection: "row",
  },
  flexDisableView: {
    width: scale(155),
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.themGreen,
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
    backgroundColor: COLORS.lightBlack,
    flexDirection: "row",
  },
  deselectText: {
    fontSize: 13,
    color: COLORS.black,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    flexWrap: "wrap",
    maxWidth: "100%",
  },
  confirmLargeText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  successImageStyle: {
    width: scale(110),
    height: verticalScale(110),
    resizeMode: "contain",
  },
  successImageView: {
    alignSelf: "center",
    marginVertical: verticalScale(25),
  },
  exerciseName: {
    color: COLORS.white,
    textAlign: "center",
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginBottom: 10,
  },
  minus: {
    flexShrink: 50,
    fontSize: 20,
  },
});

export default styles;
