import {
  ScaledSheet,
  verticalScale,
  scale,
  moderateScale,
} from "react-native-size-matters";

import { FONTS } from "../../../workout/constant";
import { COLORS } from "../../../home/constant";
const styles = ScaledSheet.create({
  container: {
    borderRadius: 10,
    marginHorizontal: 10,
    marginBottom: 10,
  },
  item: {
    width: 39,
    height: 39,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: 30,
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  setText: {
    fontSize: 22,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  setSmallText: {
    fontSize: 12,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_MEDIUM,
    alignSelf: "center",
  },
  kgView: {
    // width: 40,
    backgroundColor: COLORS.gray,
    borderRadius: 15,
    justifyContent: "center",
  },
  kgText: {
    fontSize: 30,
    color: COLORS.white,
    alignSelf: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  kgSmallText: {
    fontSize: 16,
    color: COLORS.white,
    alignSelf: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    marginHorizontal: scale(8),
    height: scale(20),
    alignSelf: "center",
  },
  countText: {
    color: COLORS.white,
    fontSize: 10,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  mainConatiner: {
    backgroundColor: COLORS.gray1,
    flex: 1,
    marginHorizontal: 5,
    borderRadius: 10,
    marginTop: 10,
  },
  listConatiner: { alignSelf: "flex-start", marginTop: 10, marginBottom: 10 },
  smallText: {
    fontSize: 16,
    fontFamily: FONTS.ARCHI_MEDIUM,
    color: COLORS.white,
  },
  noteImg: { width: 15, height: 15, marginHorizontal: 10, marginTop: 5 },
  legImg: { width: 15, height: 15 },
  bottomCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
  },
  horizontalLine: {
    borderWidth: 0.7,
    borderColor: COLORS.gray,
    marginVertical: scale(5),
    width: "98%",
    alignSelf: "center",
  },
  userHeader: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 100,
    position: "absolute",
    top: 50, // Adjust this value to position it at the top
    left: 0,
    right: 0,
    zIndex: 2,
    paddingHorizontal: 5,
    flex: 1, // Adjust as needed
    alignSelf: "flex-start",
    backgroundColor: COLORS.transparent,
  },
  userIcon: {
    height: scale(30),
    width: scale(30),
    resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 10,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  colorText: {
    color: COLORS.themGreen,
    fontSize: 25,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_BOLD,
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    height: 40,
    gap: 5,
    paddingHorizontal: 5,
  },
  smallIcon: {
    width: scale(14),
    height: scale(13),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    flexDirection: "row",
  },
  confirmText: {
    color: COLORS.black,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    flexDirection: "row",
  },
  largeTextStyle: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  sessionIcon: {
    width: scale(15),
    height: scale(15),
    resizeMode: "contain",
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    height: scale(35),
    alignSelf: "center",
  },
  userHeaderList: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 70,
    alignSelf: "flex-start",
    width: "100%",
  },
  nutrientText: {
    fontSize: 14,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginBottom: 5,
    width: "80%",
  },
  containerHeader: {
    backgroundColor: COLORS.gray1,
    marginHorizontal: 0,
    borderRadius: 10,
    marginVertical: 5,
    paddingVertical: 10,
  },
  row: {
    flexDirection: "row",
    width: "98%",
    paddingHorizontal: 10,
    gap: 5,
    marginVertical: 10,
  },
  img: { width: 38, height: 38, margin: 10 },
  starImg: { width: 15, height: 15, alignSelf: "center" },
  deleteImg: { width: 15, height: 17, alignSelf: "flex-end" },
  dangerImg: { width: 17, height: 17, alignSelf: "flex-end" },

  textUser: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  ratingView: {
    flexDirection: "row",
    // width: "0%",
    alignSelf: "center",
    justifyContent: "flex-end",
    gap: 10,
    flex: 1,
    // marginLeft:90
  },
  ratingText: {
    color: COLORS.white,
    alignSelf: "flex-end",
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  extraView: {
    width: 15,
    height: 15,
    borderWidth: 1,
    borderColor: COLORS.lightWhite,
    justifyContent: "center",
    borderRadius: 5,
  },
  execerView: {
    flexDirection: "row",
    marginLeft: 20,
    gap: 10,
    marginVertical: 20,
  },
  exerciseText: {
    fontFamily: FONTS.ARCHI_BOLD,
    fontSize: 14,
    color: COLORS.white,
  },
  shoulderText: {
    fontFamily: FONTS.ARCHI_MEDIUM,
    fontSize: 14,
    color: COLORS.white,
    width: 80,
  },
  bodyText: {
    fontFamily: FONTS.ARCHI_MEDIUM,
    fontSize: 14,
    color: COLORS.white,
    width: 80,
  },
  numberText: {
    color: COLORS.white,
    alignSelf: "flex-end",
    fontSize: 18,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  secondaryButton: {
    backgroundColor: COLORS.themGreen,
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-evenly",
    marginHorizontal: 20,
    height: 40,
  },
  secondaryButtonText: {
    color: COLORS.black,
    fontSize: 15,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  textInput: {
    height: 40,
    width: "80%",
    borderWidth: 0.5,
    borderColor: COLORS.borderColor,
    borderRadius: 10,
    color: COLORS.white,
    paddingHorizontal: 10,
  },
  listView: {
    flexDirection: "row",
    paddingHorizontal: 10,
    justifyContent: "space-between",
    marginVertical: 15,
  },
  arrowIcon: {
    width: 10,
    height: 18,
    alignSelf: "center",
    marginTop: 10,
  },
  arrowDowIcon: {
    width: 10,
    height: 6,
    alignSelf: "center",
    marginTop: 10,
  },
  confirmButton: {
    backgroundColor: COLORS.themGreen,
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(70),
    alignItems: "center",
    borderRadius: scale(15),
    padding: 7,
    height: 30,
    justifyContent: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.transparentBlack,
  },
  modalContent: {
    backgroundColor: COLORS.gray1,
    paddingVertical: 30,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
  },
  modalImage: {
    width: scale(70),
    height: scale(70),
  },
  successImage: {
    width: scale(110),
    height: scale(110),
  },

  modalText: {
    // width: scale(210),
    fontSize: 20,
    textAlign: "center",
    fontWeight: "800",
    marginVertical: 40,
    color: COLORS.white,
  },
  starImageStyle: {
    width: 30,
    height: 30,
    marginLeft: 10,
    alignSelf: "center",
    // resizeMode: 'cover',
  },
  textStyle: {
    width: 325,
    height: 90,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 30,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
  },
  smallContainer: {
    width: 250,
    height: 10,
    justifyContent: "center",
    marginTop: 20,
    borderRadius: 10,
    flexDirection: "row",
  },
  crossImage: {
    width: scale(10),
    height: scale(10),
    resizeMode: "contain",
  },
  crossIconView: {
    width: scale(15),
    padding: scale(6),
    position: "absolute",
    top: 5,
    right: 5,
    alignItems: "flex-end",
    zIndex: 1,
    padding: 10,
  },
  smallPlusIcon: {
    width: 10,
    height: 10,
    tintColor: COLORS.lightWhite,
    alignSelf: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  modalContent: {
    width: "80%",
    padding: 40,
    backgroundColor: "#353638",
    borderRadius: 10,
  },
  modalText: {
    color: COLORS.white,
    textAlign: "center",
    fontSize: 17,
    fontFamily: FONTS.ARCHI_REGULAR,
    marginBottom: 35,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
  },
});
export default styles;
