import {
  ScaledSheet,
  moderateScale,
  scale,
  verticalScale,
} from "react-native-size-matters";
import { FONTS } from "../../workout/constant/theme";
import { COLORS } from "../../home/constant/theme";
const styles = ScaledSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.themeGray,
  },
  headerBackView: {
    paddingHorizontal: 10,
    backgroundColor: COLORS.lightBlack,
  },
  headerText: {
    fontSize: 18,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
  },
  heading: {
    fontSize: 16,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  headerImage: {
    width: 25,
    height: 25,
    resizeMode: "contain",
  },
  gymView: {
    marginTop: scale(18),
    width: scale(330),
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: COLORS.lightBlack,
    borderRadius: scale(5),
    alignSelf: "center",
  },
  memberView: {
    width: scale(300),
    marginVertical: 13,
    borderTopColor: COLORS.lightGray,
    borderTopWidth: 0.6,
  },
  smallText: {
    fontSize: 13,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_LIGHT,
  },
  listItemContainer: {
    width: scale(280),
    flexDirection: "row",
    paddingVertical: 10,
    borderBottomWidth: 0.3,
    borderBottomColor: COLORS.lightGray,
  },
  flatView: {
    flex: 1,
    height: moderateScale(160),
  },
  icon: {
    width: 14,
    height: 14,
    resizeMode: "contain",
    marginRight: 16,
  },
  textContainer: {
    flex: 1,
  },
  dateText: {
    fontSize: 13,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_REGULAR,
    marginBottom: 2,
  },
  mediumText: {
    fontSize: 13,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_REGULAR,
    marginBottom: 2,
  },
  typeText: {
    fontSize: 12.5,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_REGULAR,
  },
  buttonMainView: {
    flexDirection: "row",
    alignSelf: "flex-end",
    justifyContent: "space-between",
    width: scale(130),
  },
  buttonPtView: {
    marginTop: verticalScale(15),
    flexDirection: "row",
    alignSelf: "flex-end",
    justifyContent: "space-between",
    width: scale(160),
  },
  borderTextView: {
    width: scale(60),
    alignItems: "center",
    paddingHorizontal: 1,
    paddingVertical: 3,
    backgroundColor: COLORS.lightBlack,
    borderRadius: scale(15),
    borderColor: COLORS.themGreen,
    borderWidth: 0.9,
  },
  changeButton: {
    width: scale(95),
    alignItems: "center",
    paddingHorizontal: 1,
    paddingVertical: 5,
    backgroundColor: COLORS.lightBlack,
    borderRadius: scale(15),
    borderColor: COLORS.themGreen,
    borderWidth: 0.9,
  },
  ptItemContainer: {
    width: scale(280),
    alignItems: "center",
  },
  dateView: {
    flexDirection: "row",
    width: scale(280),
    alignItems: "center",
    marginVertical: 8,
  },
  rowView: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  rowDirectionView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  userIcon: {
    width: 35,
    height: 35,
    resizeMode: "contain",
    marginRight: 10,
  },
  rateIcon: {
    width: 18,
    height: 18,
    resizeMode: "contain",
    marginRight: 13,
  },
  userName: {
    width: scale(90),
    fontSize: 14.5,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  modalContent: {
    width: scale(300),
    backgroundColor: COLORS.lightBlack,
    alignSelf: "center",
    padding: "16@ms",
    paddingVertical: scale(20),
    borderRadius: scale(8),
    elevation: 5,
  },
  buttonView: {
    width: scale(170),
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "flex-end",
    marginTop: scale(5),
  },
  buttonViewNew: {
    width: scale(170),
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "flex-end",
    marginTop: scale(10),
    marginRight: scale(22),
    gap:5,
    
  },
  modalDate: {
    fontSize: scale(13),
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.white,
  },
  modalType: {
    fontSize: 13,
    fontFamily: FONTS.ARCHI_MEDIUM,
    color: COLORS.white,
  },
  closeButton: {
    fontSize: scale(11),
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.white,
  },
  btnStyle: {
    paddingHorizontal: scale(13),
    paddingVertical: scale(5),
    borderColor: COLORS.themGreen,
    borderWidth: 1,
    borderRadius: moderateScale(15),
  },
  checkView: {
    width: scale(280),
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    padding: scale(10),
    backgroundColor: COLORS.themeGray,
    borderRadius: moderateScale(6),
    marginVertical: moderateScale(8),
  },
  headingModel: {
    fontSize: 16,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
    textAlign: "center",
  },
  borderBottomView: {
    marginVertical: scale(10),
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.lightGray,
  },
  checkImg: {
    width: 20,
    height: 20,
    resizeMode: "contain",
    marginRight: 16,
  },
  crossimg: {
    position: "absolute",
    top: 10,
    right: 0,
    zIndex: 9,
  },
  noteText: {
    fontSize: 13,
    fontFamily: FONTS.ARCHI_MEDIUM,
    color: COLORS.white,
    marginTop: 8,
  },
  searchView: {
    width: scale(270),
    backgroundColor: COLORS.black,
    alignSelf: "center",
    padding: "16@ms",
    paddingVertical: scale(8),
    borderRadius: scale(15),
    borderColor: COLORS.borderColor,
    borderWidth: 1,
    marginTop: scale(5),
    marginBottom: scale(15),
  },
  imagehold: {
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  listView: {
    flexDirection: "row",
    width: "95%",
    backgroundColor: COLORS.gray1,
    height: 50,
    borderRadius: 10,
    paddingHorizontal: 10,
    alignContent: "center",
    justifyContent: "space-between",
    alignSelf: "center",
    alignItems: "center",
  },
  informationImage: {
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  informationTextStyle: {
    color: COLORS.white,
    fontSize: 18,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  rightIcon: {
    width: 15,
    height: 15,
    tintColor: COLORS.lightWhite,
    alignSelf: "center",
  },
  itemContainer: {
    marginLeft: 5,
  },
  imagePlace: {
    width: 65,
    height: 65,
  },
  containerUser: {
    width: scale(330),
    backgroundColor: COLORS.gray1,
    paddingVertical: 20,
    borderRadius: 10,
    marginVertical: 20,
    alignSelf: "center",
  },
  img: { width: 60, height: 60, alignSelf: "center" },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  userText: {
    fontSize: 20,
    fontFamily: FONTS.ARCHI_BOLD,
    color: COLORS.white,
    alignSelf: "center",
  },
  userHeaderList: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 70,
    alignSelf: "flex-start",
    width: "100%",
    marginTop: 10,
  },
  hashView: {
    width: scale(100),
    backgroundColor: COLORS.themeGray,
    alignSelf: "center",
    paddingVertical: scale(3),
    borderRadius: scale(5),
    marginTop: scale(8),
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  sessionIcon: {
    width: scale(25),
    height: scale(25),
    resizeMode: "contain",
  },
  largeTextStyle: {
    color: COLORS.white,
    fontSize: 15,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 8,
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    height: scale(45),
    alignSelf: "center",
    marginTop: 10,
  },
  horizontalLine: {
    borderWidth: 0.7,
    borderColor: COLORS.lightWhite,
    width: scale(305),
    alignSelf: "center",
    marginTop: scale(15),
  },
  newAccountContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.themeGray,
    marginBottom: scale(80),
  },
  hashRowView: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: COLORS.themeGray,
    paddingHorizontal: scale(8),
    alignSelf: "center",
    paddingVertical: scale(5),
    borderRadius: scale(10),
    marginTop: scale(8),
  },
  logText: {
    fontSize: 12.5,
    fontFamily: FONTS.ARCHI_REGULAR,
    color: COLORS.white,
  },
  rowViewAndIcon: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    alignSelf: "center",
    marginTop: scale(8),
  },
  emailText: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_MEDIUM,
  },
  imageList: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  editView: {
    width: scale(20),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.themGreen,
    height: scale(20),
    alignSelf: "center",
    borderRadius: scale(25),
    position: "absolute",
    top: scale(53),
    right: scale(135),
    zIndex: 1,
  },
  editIcon: {
    width: 12,
    height: 12,
    resizeMode: "contain",
  },
  rejectedIcon: {
    width: 8,
    height: 8,
    resizeMode: "contain",
  },
  placeholderStyle: {
    width: scale(330),
    backgroundColor: COLORS.gray1,
    padding: 15,
    borderRadius: 10,
    marginVertical: 5,
    marginBottom: moderateScale(8),
    alignSelf: "center",
  },
  titleName: {
    color: COLORS.white,
    fontSize: 18,
    fontFamily: FONTS.ARCHI_REGULAR,
  },

  AddIconStyle: {
    width: scale(50),
    height: scale(54),
    backgroundColor: COLORS.gray1,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  bottonRowView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  borderView: {
    width: scale(250),
    justifyContent: "center",
    padding: "16@ms",
    paddingVertical: scale(8),
    borderRadius: scale(8),
    borderColor: COLORS.borderColor,
    borderWidth: 1,
    alignItems: "flex-start",
    marginTop: scale(15),
    marginBottom: scale(5),
  },
  addView: {
    width: scale(40),
    height: scale(24),
    backgroundColor: COLORS.mediumGrey,
    borderRadius: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  bottonPostion: { alignSelf: "flex-end", marginTop: scale(15) },
  textStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginRight: 43,
    width: scale(200),
  },
});
export default styles;
