import { ScaledSheet, scale } from "react-native-size-matters";
import { COLORS, FONTS } from "../../../../home/constant";

const styles = ScaledSheet.create({
  container: {
    alignItems: "flex-start",
    marginTop: 0,
    flexDirection: "row",
    alignSelf: "flex-start",
    justifyContent: "space-evenly",
    flex: 1,
    width: "100%",
  },
  headerClick: {
    width: scale(80),
    height: 40,
    backgroundColor: COLORS.gray1,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    borderRadius: 10,
  },
  buttonContainer: {
    justifyContent: "space-between",
    width: "15%",
    marginTop: 10,
    backgroundColor: COLORS.calendarColor,
    height: 53,
    width: 50,
    alignItems: "center",
    borderRadius: 15,
    marginLeft: 10,
  },
  button: {
    width: 15,
    height: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  valueText: {
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 13,
  },
  smallIcon: {
    width: scale(12),
    height: scale(12),
    resizeMode: "contain",
  },
  dowIcon: {
    width: scale(8),
    height: scale(7),
    resizeMode: "contain",
  },
  breakIcon: {
    width: scale(15),
    height: scale(12),
    resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 3,
  },
  shareIcon: {
    width: scale(15),
    height: scale(15),
    // resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 3,
  },
  lunchIcon: {
    width: scale(15),
    height: scale(12),
    // resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 3,
  },
  textCalendar: {
    color: COLORS.white,
    fontSize: 13,
  },
  trainerText: {
    marginRight: 15,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_MEDIUM,
    alignSelf: "center",
  },
  shareView: {
    width: 40,
    height: 40,
    backgroundColor: COLORS.calendarColor,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    alignSelf: "flex-end",
  },
  trainerView: {
    flexDirection: "row",
    justifyContent: "flex-end",
    width: 110,
  },
  headerOption: {
    flexDirection: "row",
    gap: 10,
    alignSelf: "flex-start",
    borderBottomWidth: 1,
    borderColor: COLORS.gray,
    height: 30,
    justifyContent: "flex-start",
    alignContent: "flex-start",
    alignItems: "flex-start",
    paddingHorizontal: 5,
    width: "100%",
  },
  dietView: {
    width: scale(110),
    height: scale(140),
    position: "absolute",
    zIndex: 2,
    top: 45,
    left: scale(102),
    backgroundColor: COLORS.gray1,
    flex: 1,
    justifyContent: "space-around",
    borderRadius: 10,
  },
});

export default styles;
