import { ScaledSheet, scale } from "react-native-size-matters";
import { COLORS } from "../constant";
import { FONTS } from "../constant";

const styles = ScaledSheet.create({
  newAccountContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: COLORS.themeGray,
    justifyContent: "center",
    marginBottom: 80,
  },
  keyboardAvoidingViewStyle: {
    flex: 1,
  },
  descriptionContainer: {
    marginTop: 16,
  },
  touchableView: {
    width: scale(140),
    height: scale(80),
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.lightBlack,
    justifyContent: "space-around",
    alignItems: "center",
    margin: 20,
    backgroundColor: COLORS.lightBlack,
  },
  selectedView: {
    borderColor: COLORS.themGreen,
    backgroundColor: COLORS.themGreen,
  },
  text: {
    marginLeft: scale(7),
    fontSize: 16,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
  },
  selectedText: {
    fontSize: 16,
    color: COLORS.black,
    fontFamily: FONTS.ARCHI_BOLD,
  },
  dumbleImg: {
    width: 32,
    height: 31,
    resizeMode: "cover",
  },
  bananaImg: {
    width: 55,
    height: 40,
    resizeMode: "contain",
  },
  searchView: {
    alignContent: "center",
    alignSelf: "center",
    alignItems: "center",
    marginTop: 10,
  },
  bodyView: {
    alignContent: "center",
    alignSelf: "center",
    alignItems: "center",
    marginLeft: 20,
    marginRight: 30,
    flexDirection: "row",
  },
  headerBodyView: {
    alignContent: "center",
    alignSelf: "center",
    alignItems: "center",
  },
  horizontalListContainer: {
    flexGrow: 1,
    paddingBottom: scale(80),
    alignSelf: "center",
  },
  headerWrite: {
    fontSize: 26,
    fontFamily: FONTS.ARCHI_BOLD,
    color: COLORS.themGreen,
    alignSelf: "center",
    marginTop: 20,
  },
  addText: {
    fontSize: 26,
    fontFamily: FONTS.ARCHI_BOLD,
    color: COLORS.white,
    alignSelf: "center",
  },
  addTouchable: {
    width: 30,
    height: 30,
    borderRadius: 4,
    backgroundColor: COLORS.calendarColor,
    marginLeft: 10,
  },
  buttonView: {
    flexDirection: "row",
    gap: 25,
    padding: 30,
    marginRight: 30,
    justifyContent: "center",
  },
  userIcon: {
    height: scale(30),
    width: scale(30),
    resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 10,
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  reservTextHead: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginLeft: scale(6),
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    height: 30,
  },
  smallIcon: {
    width: scale(12),
    height: scale(11),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  largeTextStyle: {
    color: COLORS.white,
    fontSize: 15,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  colorText: {
    color: COLORS.themGreen,
    fontSize: 25,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    height: scale(35),
    alignSelf: "center",
  },
  sessionIcon: {
    width: scale(15),
    height: scale(11),
    resizeMode: "contain",
  },
  userHeader: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 100,
    position: "absolute",
    top: 50,
    left: 0,
    right: 0,
    zIndex: 2,
    paddingHorizontal: 5,
    backgroundColor: COLORS.transparent,
  },
  addYellowview: {
    backgroundColor: COLORS.themGreen,
    position: "absolute",
    bottom: scale(100),
    right: 15,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
    padding: 16,
  },
  pluseText: {
    color: "black",
    fontSize: 30,
    fontWeight: "400",
  },
  centeredView: {
    width: "100%",
    position: "absolute",
    borderRadius: 9,
    padding: 1,
    alignItems: "flex-end",
    height: "100%",
    justifyContent: "flex-end",
    bottom: 0,
  },
  modalPlusView: {
    marginBottom: 130,
    marginRight: 85,
  },
  modalView: {
    width: scale(160),
    flexDirection: "row",
    borderRadius: 25,
    padding: 5,
    alignItems: "center",
    elevation: 5,
  },
  modalWorkoutView: {
    width: scale(110),
    flexDirection: "row",
    borderRadius: 25,
    padding: 10,
    alignItems: "center",
    elevation: 5,
    backgroundColor: COLORS.calendarColor,
    borderColor: COLORS.themGreen,
    borderWidth: 2,
  },
  modalText: {
    textAlign: "center",
    fontSize: scale(12),
    color: COLORS.black,
    fontWeight: "500",
    marginLeft: scale(4),
  },
  modelIcon: {
    width: scale(15),
    height: scale(15),
    resizeMode: "contain",
  },
  workoutButtonContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    zIndex: 2,
  },
  scrollV: {
    marginTop: scale(-140),
    zIndex: -1,
  },
  headerTrainer: {
    flexDirection: "row",
    zIndex: 3,
    height: scale(200),
    overflow: "hidden",
    position: "relative",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.transparentBlack,
  },
  modalContent: {
    backgroundColor: COLORS.gray1,
    paddingVertical: 30,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
  },
  modalImage: {
    width: scale(70),
    height: scale(70),
  },
  successImage: {
    width: scale(110),
    height: scale(110),
  },
  starImageStyle: {
    width: 30,
    height: 30,
    marginLeft: 10,
    alignSelf: "center",
  },
  textStyle: {
    width: 325,
    height: 90,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 30,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
  },
  smallContainer: {
    width: 250,
    height: 10,
    justifyContent: "center",
    marginTop: 20,
    borderRadius: 10,
    flexDirection: "row",
  },
  crossImage: {
    width: scale(10),
    height: scale(10),
    resizeMode: "contain",
  },
  crossIconView: {
    width: scale(15),
    padding: scale(6),
    position: "absolute",
    top: 1,
    right: 5,
    alignItems: "flex-end",
    zIndex: 1,
  },
  smallPlusIcon: {
    width: 10,
    height: 10,
    tintColor: COLORS.lightWhite,
    alignSelf: "center",
  },
  modalTextUpload: {
    textAlign: "center",
    fontSize: 20,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
    marginLeft: scale(4),
    marginVertical: 10,
  },
  doneText: {
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    marginRight: 45,
  },
  minus: {
    flexShrink: 50,
    fontSize: 20,
  },
  exerciseName: {
    color: COLORS.white,
    textAlign: "center",
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginBottom: 10,
  },
});

export default styles;
