import {
  ScaledSheet,
  verticalScale,
  scale,
  moderateScale,
} from "react-native-size-matters";

import { COLORS, FONTS } from "../../constant";

const styles = ScaledSheet.create({
  modalContainer: {
    // flex: 1,

    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: '',
  },
  modalContent: {
    backgroundColor: COLORS.themeGray,
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
    marginTop: scale(200),
  },
  modalImage: {
    width: scale(100),
    height: scale(100),
  },
  modalText: {
    // width: scale(210),
    fontSize: 20,
    textAlign: "center",
    fontWeight: "800",
    marginVertical: 7,
    color: COLORS.white,
  },
  starImageStyle: {
    width: 30,
    height: 35,
    marginLeft: 10,
    alignSelf: "center",
    resizeMode: "contain",
  },
  textStyle: {
    width: 325,
    height: 90,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 30,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
  },
  smallContainer: {
    width: 250,
    height: 60,
    backgroundColor: COLORS.calendarColor,
    justifyContent: "center",
    marginTop: 20,
    borderRadius: 10,
    flexDirection: "row",
  },
  modelViewcontainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  reservTextHead: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginLeft: scale(6),
  },
  userIcon: {
    height: verticalScale(30),
    width: scale(33),
    resizeMode: "contain",
    alignSelf: "center",
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  crossIconView: {
    width: scale(15),
    padding: scale(6),
    position: "absolute",
    top: 1,
    right: 5,
    alignItems: "flex-end",
    zIndex: 1,
  },
  RecentlyView: {
    padding: scale(6),
    marginTop: verticalScale(10),
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: scale(8),
  },
  reserveIcon: {
    width: scale(23),
    height: scale(23),
    resizeMode: "contain",
  },
  timeText: {
    fontSize: 13,
    marginBottom: verticalScale(4),
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  smallIcon: {
    width: scale(12),
    height: verticalScale(11),
    resizeMode: "contain",
  },
  sessionIcon: {
    width: scale(14),
    height: verticalScale(9),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  confirmText: {
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    color: COLORS.black,
  },
  confirmLargeText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  rejectText: {
    fontSize: 12,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.white,
  },
  boxView: {
    alignItems: "center",
    width: scale(70),
    height: scale(52),
    borderRadius: verticalScale(2),
    backgroundColor: COLORS.calendarColor,
    marginLeft: scale(5),
    padding: scale(8),
    justifyContent: "space-around",
  },
  confirmStyle: {
    alignItems: "center",
    width: 70,
    height: 27,
    borderRadius: verticalScale(15),
    marginLeft: scale(10),
    padding: scale(3),
    justifyContent: "center",
  },
  confirmButton: {
    backgroundColor: COLORS.themGreen,
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    borderRadius: scale(15),
    padding: 7,
    height: 35,
    justifyContent: "center",
  },
  cancelButton: {
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    padding: 7,
    borderWidth: 1,
    borderColor: COLORS.lightWhite,
    borderRadius: scale(15),
  },

  // --------- Model reject --
  TextReasone: {
    color: COLORS.white,
    fontSize: scale(15),
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginBottom: 10,
  },
  textSmallReasone: {
    color: COLORS.white,
    fontSize: scale(13),
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginLeft: scale(5),
  },
  radioIcon: {
    width: scale(15),
    height: scale(15),
    resizeMode: "contain",
  },
  searchView: {
    marginTop: verticalScale(14),
    paddingHorizontal: scale(15),
    padding: moderateScale(8),
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    width: scale(310),
    backgroundColor: COLORS.black,
    borderColor: COLORS.gray,
    borderWidth: 1,
    borderRadius: scale(19),
  },
  rejectedText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  reasonRejectContain: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: scale(310),
  },
  // -------- Model cancel -----
  centerModal: {
    marginTop: verticalScale(10),
    width: scale(320),
    alignSelf: "center",
    borderRadius: scale(6),
    padding: verticalScale(6),
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.white,
    marginHorizontal: verticalScale(8),
    width: scale(4),
    height: verticalScale(10),
  },
  horizontalLine: {
    borderWidth: 1,
    borderColor: COLORS.gray,
    marginVertical: scale(10),
    marginLeft: scale(10),
    width: scale(220),
    alignSelf: "center",
  },
  item: {
    width: scale(350),
    height: 80,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    backgroundColor: COLORS.gray,
    padding: 10,
    borderRadius: 8,
  },
  image: {
    width: scale(45),
    height: scale(43),
    resizeMode: "contain",
    marginVertical: 100,
  },
  column: {
    marginLeft: 10,
    height: 52,
    justifyContent: "space-around",
    width: 250,
  },
  headerStatus: {
    backgroundColor: COLORS.lightBlack,
    marginHorizontal: 20,
    marginTop: 10,
    borderStartEndRadius: 8,
    borderTopLeftRadius: 8,
    width: scale(350),
    alignSelf: "center",
  },
  titleNotify: {
    fontSize: 15,
    fontFamily: FONTS.ARCHI_MEDIUM,
    color: COLORS.white,
  },
  timeView: {
    width: 70,
    justifyContent: "flex-start",
    alignItems: "flex-end",
    height: 52,
  },
  minText: {
    fontSize: 10,
    color: COLORS.placeholderColor,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  statusReserve: {
    width: scale(19),
    height: scale(23),
    resizeMode: "contain",
  },
  buttonView: {
    alignSelf: "flex-end",
    marginRight: 20,
    flexDirection: "row",
    marginTop: 10,
  },
  availableText: {
    color: COLORS.white,
    marginHorizontal: 20,
    fontFamily: FONTS.ARCHI_BOLD,
    fontSize: 17,
    marginBottom: 15,
  },
  confirmModal: {
    width: scale(330),
    alignSelf: "center",
    justifyContent: "center",
    marginTop: scale(100),
    borderRadius: scale(8),
    paddingVertical: scale(30),
    backgroundColor: COLORS.lightBlack,
    margin: 10,
    height: scale(480),
  },
  crossImage: {
    width: scale(12),
    height: verticalScale(12),
    resizeMode: "contain",
  },
});

export default styles;
