import {
  ScaledSheet,
  moderateScale,
  scale,
  verticalScale,
} from "react-native-size-matters";
import { COLORS, FONTS } from "../constant";

const styles = ScaledSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: moderateScale(10),
  },
  buttonText: {
    fontSize: moderateScale(16),
    color: "blue",
  },
  monthYear: {
    fontSize: moderateScale(18),
    fontWeight: "bold",
    color: COLORS.black,
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  dayCell: {
    width: "14.28%",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: COLORS.borderColor,
    backgroundColor: COLORS.calendarColor,
    height: verticalScale(93),
    alignContent: "flex-start",
  },
  dayText: {
    fontSize: moderateScale(14),
    color: COLORS.white,
    position: "relative",
    // top: verticalScale(-4),
  },
  dayOfWeek: {
    fontWeight: "bold",
    color: COLORS.white,
  },
  nextMonth: {
    fontSize: moderateScale(14),
    color: COLORS.calendarColor,
    position: "relative",
    top: verticalScale(-30),
  },
  weekNameCell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  weekNameRow: {
    width: "14.28%",
    height: verticalScale(50),
    justifyContent: "space-evenly",
    marginTop: verticalScale(200),
    borderWidth: 0.5,
    borderColor: COLORS.borderColor,
    backgroundColor: COLORS.calendarColor,
    marginTop: verticalScale(5),
    borderTopWidth: 0,
  },
  weekNameText: {
    fontWeight: "700",
    fontSize: moderateScale(13),
    color: COLORS.borderColor,
    textAlign: "center",
  },
  taskText: {
    fontSize: moderateScale(12),
  },
  taskView: {
    flexDirection: "row",
    marginTop: verticalScale(3),
    marginHorizontal: moderateScale(4),
    borderRadius: moderateScale(4),
    width: moderateScale(50),
    height: moderateScale(20),
    alignItems: "center",
    backgroundColor: COLORS.calendarColor,
  },
  taskImage: {
    height: verticalScale(13),
    width: scale(14),
    resizeMode: "contain",
    marginHorizontal: moderateScale(4),
  },
  viewContainer: {
    alignSelf: "center",
    justifyContent: "center",
  },

  // ------ calender screen style ----
  containerCalender: {
    flex: 1,
    backgroundColor: COLORS.headerColor,
    justifyContent: "flex-start",
  },
  addYellowview: {
    backgroundColor: COLORS.themGreen,
    position: "absolute",
    bottom: scale(170),
    right: 15,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
    padding: 16
  },
  calenderContainer: {
    alignSelf: "center",
    justifyContent: "center",
    flex: 1,
  },
  pluseText: {
    color: "black",
    fontSize: 30,
    fontWeight: "400",
  },

  // ------- model ------
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  centeredView: {
    width: "100%",
    position: "absolute",
    borderRadius: 9,
    padding: 1,
    alignItems: "flex-end",
    flex: 1,
    zIndex: 2,
    height: "100%",
    alignContent: "flex-end",
    justifyContent: "flex-end",
    bottom: 0,
  },
  modalPlusView: { marginBottom: 130, marginRight: 85 },
  modalView: {
    width: scale(110),
    flexDirection: "row",
    borderRadius: 25,
    padding: 10,
    alignItems: "center",
    elevation: 5,
  },
  modalWorkoutView: {
    width: scale(110),
    flexDirection: "row",
    borderRadius: 25,
    padding: 10,
    alignItems: "center",
    elevation: 5,
    backgroundColor: COLORS.calendarColor,
    borderColor: COLORS.themGreen,
    borderWidth: 2,
  },
  modalText: {
    textAlign: "center",
    fontSize: scale(12),
    color: COLORS.black,
    fontWeight: "500",
    marginLeft: verticalScale(4),
  },
  modelIcon: {
    width: scale(15),
    height: scale(15),
    resizeMode: "contain",
    alignSelf: "center",
  },

  viewModal: {
    width: scale(350),
    alignSelf: "center",
    justifyContent: "center",
    marginTop: scale(160),
    borderRadius: scale(8),
    paddingVertical: scale(30),
    backgroundColor: COLORS.lightBlack,
    margin: 10,
  },

  confirmModal: {
    width: scale(330),
    alignSelf: "center",
    justifyContent: "center",
    marginTop: scale(100),
    borderRadius: scale(8),
    paddingVertical: scale(30),
    backgroundColor: COLORS.lightBlack,
    margin: 10,
    height: scale(480),
  },
  crossImage: {
    width: scale(12),
    height: verticalScale(12),
    resizeMode: "contain",
  },

  // -------- Modal ------
  modelViewcontainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  reservTextHead: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginLeft: scale(6),
  },
  userIcon: {
    height: verticalScale(30),
    width: scale(30),
    resizeMode: "contain",
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  crossIconView: {
    width: scale(15),
    padding: scale(6),
    position: "absolute",
    top: 1,
    right: 5,
    alignItems: "flex-end",
    zIndex: 1,
  },
  RecentlyView: {
    padding: scale(6),
    marginTop: verticalScale(10),
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: scale(8),
  },
  reserveIcon: {
    width: scale(23),
    height: verticalScale(23),
    resizeMode: "contain",
  },
  timeText: {
    fontSize: 13,
    marginBottom: verticalScale(4),
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  smallIcon: {
    width: scale(12),
    height: verticalScale(12),
    resizeMode: "contain",
  },
  sessionIcon: {
    width: scale(14),
    height: verticalScale(13),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 12,
    fontFamily: FONTS.ARCHI_MEDIUM,
  },
  confirmText: {
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    color: COLORS.black,
  },
  confirmLargeText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  rejectText: {
    fontSize: 12,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.white,
  },
  boxView: {
    alignItems: "center",
    width: scale(70),
    height: scale(52),
    borderRadius: verticalScale(2),
    backgroundColor: COLORS.calendarColor,
    marginLeft: scale(5),
    padding: scale(8),
    justifyContent: "space-around",
  },
  confirmStyle: {
    alignItems: "center",
    width: 70,
    height: 27,
    borderRadius: verticalScale(15),
    marginLeft: scale(10),
    padding: scale(3),
    justifyContent: "center",
  },
  confirmButton: {
    backgroundColor: COLORS.themGreen,
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    borderRadius: scale(15),
    padding: 7,
    height: 35,
    justifyContent: "center",
  },
  cancelButton: {
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    padding: 7,
    borderWidth: 1,
    borderColor: COLORS.lightWhite,
    borderRadius: scale(15),
  },

  // --------- Model reject --
  TextReasone: {
    color: COLORS.white,
    fontSize: scale(15),
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginBottom: 10,
  },
  textSmallReasone: {
    color: COLORS.white,
    fontSize: scale(13),
    fontWeight: "500",
    marginLeft: scale(9),
  },
  radioIcon: {
    width: scale(12),
    height: verticalScale(12),
    resizeMode: "contain",
  },
  searchView: {
    marginTop: verticalScale(14),
    paddingHorizontal: scale(15),
    padding: moderateScale(8),
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    width: scale(310),
    backgroundColor: COLORS.black,
    borderColor: COLORS.gray,
    borderWidth: 1,
    borderRadius: scale(19),
  },
  rejectedText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  reasonRejectContain: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: scale(310),
  },
  // -------- Model cancel -----
  centerModal: {
    marginTop: verticalScale(10),
    width: scale(320),
    alignSelf: "center",
    borderRadius: scale(6),
    padding: verticalScale(6),
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.white,
    marginHorizontal: verticalScale(8),
    width: scale(4),
    height: verticalScale(10),
  },
  horizontalLine: {
    borderWidth: 1,
    borderColor: COLORS.gray,
    marginVertical: scale(8),
    marginLeft: scale(10),
    width: scale(220),
    alignSelf: "center",
  },
  minus:{
    flexShrink:50,
    fontSize:20
  }
});

export default styles;
