import {
  ScaledSheet,
  verticalScale,
  scale,
  moderateScale,
} from "react-native-size-matters";

import { COLORS, FONTS } from "../../constant";

const styles = ScaledSheet.create({
  container: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: COLORS.gray1,
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 10,
    marginVertical: 20,
  },
  item: {
    width: 39,
    height: 39,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  imageContainer: {
    // Additional styles for views with images
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderRadius: 5,
  },
  touchableContainer: {
    width: 35,
    height: 85,
    backgroundColor: COLORS.black,
    alignSelf: "flex-end",
    justifyContent: "center",
    alignItems: "center",
    margin: 2,
    borderTopEndRadius: 10,
    borderEndEndRadius: 10,
  },
  setView: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "80%",
    marginTop: 30,
  },
  setTextView: {
    width: 50,
    height: 50,
    backgroundColor: COLORS.gray1,
    borderRadius: 45,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },
  setText: {
    fontSize: 20,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  setSmallText: {
    fontSize: 12,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_MEDIUM,
    alignSelf: "center",
  },
  kgView: {
    // width: 40,
    backgroundColor: COLORS.gray,
    borderRadius: 15,
    justifyContent: "center",
  },
  kgText: {
    fontSize: 30,
    color: COLORS.white,
    alignSelf: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  kgSmallText: {
    fontSize: 16,
    color: COLORS.white,
    alignSelf: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    marginHorizontal: scale(8),
    height: scale(50),
    alignSelf: "center",
  },
  arrowIcon: {
    width: 10,
    height: 18,
  },
  arrowDowIcon: {
    width: 10,
    height: 6,
  },
  ImageView: {
    width: scale(15),
    height: scale(15),
    // paddingVertical: scale(1),
    borderRadius: scale(8),
    backgroundColor: COLORS.Lightred,
    alignSelf: "flex-end",
    alignItems: "center",
    position: "absolute",
    top: -7,
    left: 25,
    justifyContent: "center",
  },
  countText: {
    color: COLORS.white,
    fontSize: 10,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  mainConatiner: {
    backgroundColor: COLORS.gray1,
    flex: 1,
    marginHorizontal: 5,
    borderRadius: 10,
    marginTop: 10,
  },
  listConatiner: { alignSelf: "flex-start", marginTop: 10, marginBottom: 10 },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.transparentBlack,
  },
  modalContent: {
    backgroundColor: COLORS.themeGray,
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
  },
  modalImage: {
    width: scale(100),
    height: scale(100),
    alignSelf:'center'
  },
  modalText: {
    // width: scale(210),
    fontSize: 20,
    textAlign: "center",
    fontWeight: "800",
    marginTop: 10,
    color: COLORS.white,
  },
  starImageStyle: {
    width: 30,
    height: 30,
    marginLeft: 10,
    alignSelf: "center",
    // resizeMode: 'cover',
  },
  textStyle: {
    width: 325,
    height: 90,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 30,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
  },
  smallContainer: {
    width: 250,
    height: 60,
    backgroundColor: COLORS.calendarColor,
    justifyContent: "center",
    marginTop: 20,
    borderRadius: 10,
    flexDirection: "row",
  },
  modelViewcontainer: {
    flex: 1,
    backgroundColor: COLORS.themeGray,
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  reservTextHead: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginLeft: scale(6),
  },
  userIcon: {
    height: verticalScale(30),
    width: scale(33),
    resizeMode: "contain",
    alignSelf: "center",
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  crossIconView: {
    width: scale(15),
    padding: scale(6),
    position: "absolute",
    top: 1,
    right: 0,
    alignItems: "flex-end",
    zIndex: 1,
  },
  RecentlyView: {
    padding: scale(6),
    marginTop: verticalScale(10),
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: scale(8),
  },
  reserveIcon: {
    width: scale(23),
    height: scale(23),
    resizeMode: "contain",
  },
  timeText: {
    fontSize: 13,
    marginBottom: verticalScale(4),
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  smallIcon: {
    width: scale(12),
    height: verticalScale(11),
    resizeMode: "contain",
  },
  sessionIcon: {
    width: scale(14),
    height: verticalScale(9),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  confirmText: {
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    color: COLORS.black,
  },
  confirmLargeText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  rejectText: {
    fontSize: 12,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.white,
  },
  boxView: {
    alignItems: "center",
    width: scale(70),
    height: scale(52),
    borderRadius: verticalScale(2),
    backgroundColor: COLORS.calendarColor,
    marginLeft: scale(5),
    padding: scale(8),
    justifyContent: "space-around",
  },
  confirmStyle: {
    alignItems: "center",
    width: 70,
    height: 27,
    borderRadius: verticalScale(15),
    marginLeft: scale(10),
    padding: scale(3),
    justifyContent: "center",
  },
  confirmButton: {
    backgroundColor: COLORS.themGreen,
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    borderRadius: scale(15),
    padding: 7,
    height: 35,
    justifyContent: "center",
  },
  cancelButton: {
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    padding: 7,
    borderWidth: 1,
    borderColor: COLORS.lightWhite,
    borderRadius: scale(15),
  },

  // --------- Model reject --
  TextReasone: {
    color: COLORS.white,
    fontSize: scale(15),
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginBottom: 10,
  },
  textSmallReasone: {
    color: COLORS.white,
    fontSize: scale(13),
    fontWeight: "500",
    marginLeft: scale(9),
  },
  radioIcon: {
    width: scale(12),
    height: verticalScale(12),
    resizeMode: "contain",
  },
  searchView: {
    marginTop: verticalScale(14),
    paddingHorizontal: scale(15),
    padding: moderateScale(8),
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    width: scale(310),
    backgroundColor: COLORS.black,
    borderColor: COLORS.gray,
    borderWidth: 1,
    borderRadius: scale(19),
  },
  rejectedText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  reasonRejectContain: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: scale(310),
  },
  confirmModal: {
    width: scale(330),
    alignSelf: "center",
    justifyContent: "center",
    marginTop: scale(150),
    borderRadius: scale(8),
    paddingVertical: scale(30),
    backgroundColor: COLORS.lightBlack,
    margin: 10,
    height: scale(410),
  },
  crossImage: {
    width: scale(12),
    height: verticalScale(12),

  },
   buttonView: {
    flexDirection: "row",
    gap:20,
    justifyContent: "flex-end",
    alignSelf: "flex-end",
    marginRight: scale(20),
  },
  modelViewcontainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  reservTextHead: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    marginLeft: scale(6),
  },
  userIcon: {
    height: verticalScale(30),
    width: scale(33),
    resizeMode: "contain",
    alignSelf: "center",
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  
  RecentlyView: {
    padding: scale(6),
    marginTop: verticalScale(10),
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: scale(8),
  },
  reserveIcon: {
    width: scale(23),
    height: scale(23),
    resizeMode: "contain",
  },
  timeText: {
    fontSize: 13,
    marginBottom: verticalScale(4),
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  smallIcon: {
    width: scale(12),
    height: verticalScale(11),
    resizeMode: "contain",
  },
  sessionIcon: {
    width: scale(14),
    height: verticalScale(9),
    resizeMode: "contain",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  confirmText: {
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    color: COLORS.black,
  },
  confirmLargeText: {
    color: COLORS.white,
    fontSize: 26,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  rejectText: {
    fontSize: 12,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.white,
  },
  boxView: {
    alignItems: "center",
    width: scale(70),
    height: scale(52),
    borderRadius: verticalScale(2),
    backgroundColor: COLORS.calendarColor,
    marginLeft: scale(5),
    padding: scale(8),
    justifyContent: "space-around",
  },
  confirmStyle: {
    alignItems: "center",
    width: 70,
    height: 27,
    borderRadius: verticalScale(15),
    marginLeft: scale(10),
    padding: scale(3),
    justifyContent: "center",
  },
  confirmButton: {
    backgroundColor: COLORS.themGreen,
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    borderRadius: scale(15),
    padding: 7,
    height: 35,
    justifyContent: "center",
  },
  cancelButton: {
    alignSelf: "center",
    marginTop: scale(0),
    width: scale(80),
    alignItems: "center",
    padding: 7,
    borderWidth: 1,
    borderColor: COLORS.lightWhite,
    borderRadius: scale(15),
  },
});

export default styles;
