import { ScaledSheet, scale } from "react-native-size-matters";
import { COLORS, FONTS } from "../../home/constant";

const styles = ScaledSheet.create({
  newAccountContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: COLORS.themeGray,
  },
  keyboardAvoidingViewStyle: {
    flex: 1,
  },
  descriptionContainer: {
    marginTop: 16,
  },
  headingText: {
    width: scale(165),
    color: COLORS.white,
    fontSize: scale(17),
    fontWeight: "bold",
    marginLeft: scale(15),
  },
  container: {
    flex: 1,
    padding: 10,
  },
  messageContainer: {
    backgroundColor: COLORS.calendarColor,
    padding: 5,
    marginVertical: 5,
    borderRadius: 10,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 50,
    width: scale(320),
    alignSelf: "flex-end",
    marginTop: 10,
  },
  input: {
    flex: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    color: COLORS.white,
  },
  inputBorder: {
    flex: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    color: COLORS.white,
    flexDirection: "row",
    backgroundColor: COLORS.gray1,
  },
  sentMessage: {
    alignSelf: "flex-end",
    flex: 1,
    borderColor: "#ccc",
    borderTopEndRadius: 20,
    borderBottomStartRadius: 20,
    borderTopStartRadius: 10,
    paddingHorizontal: 5,
    color: COLORS.white,
    backgroundColor: COLORS.white,
    marginTop: 5,
    width: "auto",
    alignItems: "flex-end",
    paddingVertical: -20,
  },
  receivedMessage: {
    alignSelf: "flex-start",
    flexWrap: 1,
    borderColor: "#ccc",
    borderTopEndRadius: 10,
    borderBottomEndRadius: 20,
    borderTopStartRadius: 10,
    padding: 5,
    backgroundColor: COLORS.chatGray,
    marginTop: 10,
    justifyContent: "flex-start",
  },
  sentMessageText: {
    alignSelf: "flex-end",
    borderColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    color: COLORS.black,
    flex: 1,
    alignItems: "flex-end",
  },

  receivedMessageText: {
    alignSelf: "flex-start",
    flex: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    color: COLORS.white,
  },
  sendButton: {
    marginLeft: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: COLORS.themGreen,
    borderRadius: 100,
  },
  sendButtonImage: {
    width: 20,
    height: 17,
    color: COLORS.black,
    fontWeight: "bold",
  },
  profileImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 10,
    marginTop: 10,
  },
  chatImage: {
    width: 150,
    height: 120,
    borderRadius: 20,
    marginRight: 10,
    resizeMode: "contain",
  },
  chatView: { flexDirection: "row" },
  thumbnailImage: {
    width: 40,
    height: 40,
    borderRadius: 5,
    marginRight: 10,
  },
  selectButton: {
    width: scale(100),
    height: 40,
    backgroundColor: COLORS.themGreen,
    position: "absolute",
    top: 180,
    zIndex: 2,
    alignItems: "center",
    left: 130,
    borderRadius: 100,
    justifyContent: "center",
  },
  upload: {
    width: scale(30),
    height: scale(22),
  },
  uploadText: {
    color: COLORS.white,
    flexSize: 16,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  uploadView: {
    flexDirection: "row",
    width: scale(53),
    height: scale(45),
    backgroundColor: COLORS.calendarColor,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    alignSelf: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.transparentBlack,
  },
  modalContent: {
    backgroundColor: COLORS.gray1,
    paddingVertical: 30,
    borderRadius: 10,
    alignItems: "center",
    width: scale(330),
  },
  modalImage: {
    width: scale(70),
    height: scale(70),
  },
  modalText: {
    // width: scale(210),
    fontSize: 14,
    textAlign: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
    color: COLORS.black,
    alignSelf: "center",
  },
  starImageStyle: {
    width: 30,
    height: 30,
    marginLeft: 10,
    alignSelf: "center",
    // resizeMode: 'cover',
  },
  textStyle: {
    width: 325,
    height: 90,
    borderColor: "gray",
    borderWidth: 1,
    padding: 10,
    marginTop: 30,
    borderRadius: 10,
    marginBottom: 20,
    color: COLORS.white,
  },
  smallContainer: {
    width: 250,
    height: 30,
    justifyContent: "center",
    marginVertical: 30,
    borderRadius: 10,
  },
  crossImage: {
    width: scale(10),
    height: scale(10),
    resizeMode: "contain",
  },
  imageHolder: {
    width: scale(17),
    height: scale(17),
    resizeMode: "contain",
  },
  crossIconView: {
    width: scale(15),
    padding: scale(6),
    position: "absolute",
    top: 1,
    right: 5,
    alignItems: "flex-end",
    zIndex: 1,
  },
  doneText: {
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    fontSize: 12,
    marginRight: 45,
  },
  modalTextUpload: {
    textAlign: "center",
    fontSize: 20,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_BOLD,
    marginLeft: scale(4),
    marginVertical: 10,
  },
  messageContainer: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  messageText: {
    fontSize: 16,
  },
  loadingContainer: {
    padding: 10,
    alignItems: "center",
  },
  backButtonView: { marginVertical: 5 },
});

export default styles;
