import {
  ScaledSheet,
  verticalScale,
  scale,
  moderateScale,
} from "react-native-size-matters";

import { FONTS } from "../../../workout/constant";
import { COLORS } from "../../../home/constant";
const styles = ScaledSheet.create({
  container: {
    backgroundColor: COLORS.gray1,
    borderRadius: 10,
    marginHorizontal: 10,
    marginBottom: 10,
  },
  item: {
    width: 39,
    height: 39,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: 30,
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  setText: {
    fontSize: 22,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  setSmallText: {
    fontSize: 12,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_MEDIUM,
    alignSelf: "center",
  },
  kgView: {
    // width: 40,
    backgroundColor: COLORS.gray,
    borderRadius: 15,
    justifyContent: "center",
  },
  kgText: {
    fontSize: 30,
    color: COLORS.white,
    alignSelf: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  kgSmallText: {
    fontSize: 16,
    color: COLORS.white,
    alignSelf: "center",
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    marginHorizontal: scale(8),
    height: scale(20),
    alignSelf: "center",
  },
  countText: {
    color: COLORS.white,
    fontSize: 10,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    textAlign: "center",
  },
  mainConatiner: {
    backgroundColor: COLORS.gray1,
    flex: 1,
    marginHorizontal: 5,
    borderRadius: 10,
    marginTop: 10,
  },
  listConatiner: { alignSelf: "flex-start", marginTop: 10, marginBottom: 10 },
  smallText: {
    fontSize: 16,
    fontFamily: FONTS.ARCHI_MEDIUM,
    color: COLORS.white,
  },
  noteImg: { width: 15, height: 15, marginHorizontal: 10, marginTop: 5 },
  legImg: { width: 15, height: 15 },
  bottomCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
  },
  horizontalLine: {
    borderWidth: 0.7,
    borderColor: COLORS.gray,
    marginVertical: scale(5),
    width: "98%",
    alignSelf: "center",
  },
  userHeader: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 100,
    position: "absolute",
    top: 50, // Adjust this value to position it at the top
    left: 0,
    right: 0,
    zIndex: 2,
    paddingHorizontal: 5,
    flex: 1, // Adjust as needed
    alignSelf: "flex-start",
    backgroundColor: COLORS.transparent,
  },
  userIcon: {
    height: scale(30),
    width: scale(30),
    resizeMode: "contain",
    alignSelf: "center",
    marginBottom: 10,
  },
  userTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  colorText: {
    color: COLORS.themGreen,
    fontSize: 25,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  requestTextStyle: {
    color: COLORS.white,
    fontSize: 19,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  requestTextView: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    height: 30,
    gap: 5,
  },
  smallIcon: {
    width: 17,
    height: 16,
    resizeMode: "contain",
  },
  smallPlusIcon: {
    width: 10,
    height: 10,
    tintColor: COLORS.lightWhite,
    alignSelf: "center",
  },
  smallTextStyle: {
    color: COLORS.white,
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    flexDirection: "row",
  },
  largeTextStyle: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginTop: 10,
  },
  sessionIcon: {
    width: scale(15),
    height: scale(15),
    resizeMode: "contain",
  },
  verticalLine: {
    borderRightWidth: 0.7,
    borderRightColor: COLORS.lightWhite,
    height: scale(35),
    alignSelf: "center",
  },
  userHeaderList: {
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    height: 70,
    alignSelf: "flex-start",
    width: "100%",
  },
  nutrientText: {
    fontSize: 14,
    color: COLORS.white,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
    marginBottom: 5,
    width: "80%",
  },
  containerHeader: {
    backgroundColor: COLORS.gray1,
    marginHorizontal: 0,
    borderRadius: 10,
    marginVertical: 10,
  },
  row: { flexDirection: "row", width: "100%" },
  img: { width: 38, height: 38, margin: 10, borderRadius: 100 },
  starImg: { width: 15, height: 15, alignSelf: "center" },
  textUser: {
    color: COLORS.white,
    fontSize: 18,
    fontFamily: FONTS.ARCHI_SEMBOLD,
    alignSelf: "center",
  },
  ratingView: {
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "flex-end",
    gap: 10,
    flex: 1,
    marginRight: 10,
  },
  ratingText: {
    color: COLORS.white,
    alignSelf: "flex-end",
    fontSize: 14,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
  extraView: {
    width: 15,
    height: 15,
    borderWidth: 1,
    borderColor: COLORS.lightWhite,
    borderRadius: 5,
    justifyContent: "center",
  },
  execerView: {
    flexDirection: "row",
    marginLeft: 20,
    gap: 10,
    marginVertical: 20,
  },
  exerciseText: {
    fontFamily: FONTS.ARCHI_BOLD,
    fontSize: 14,
    color: COLORS.white,
  },
  shoulderText: {
    fontFamily: FONTS.ARCHI_MEDIUM,
    fontSize: 14,
    color: COLORS.white,
    width: 80,
  },
  bodyText: {
    fontFamily: FONTS.ARCHI_MEDIUM,
    fontSize: 14,
    color: COLORS.white,
    width: 80,
  },
  numberText: {
    color: COLORS.white,
    alignSelf: "flex-end",
    fontSize: 18,
    fontFamily: FONTS.ARCHI_SEMBOLD,
  },
});
export default styles;
